import { StyleSheet } from 'react-native';

import { LUNA_COLORS } from '@/src/theme/colors';
import { borderRadius, spacing } from '@/src/theme/spacing';
import { fontSize, fontWeight } from '@/src/theme/typography';

/** Modales LUNA — palette simple bleu clair (#A7EBF2), fond blanc, pied léger. */
export const lunaModalStyles = StyleSheet.create({
  overlayCenter: {
    flex: 1,
    backgroundColor: 'rgba(1, 28, 64, 0.35)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.lg,
  },
  overlaySheet: {
    flex: 1,
    backgroundColor: 'rgba(1, 28, 64, 0.35)',
    justifyContent: 'flex-end',
  },
  card: {
    width: '100%',
    maxWidth: 480,
    backgroundColor: LUNA_COLORS.surface,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: LUNA_COLORS.primary,
    overflow: 'hidden',
    maxHeight: '90%',
  },
  cardSheet: {
    width: '100%',
    backgroundColor: LUNA_COLORS.surface,
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: LUNA_COLORS.primary,
    maxHeight: '92%',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    backgroundColor: LUNA_COLORS.primary,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(84, 172, 191, 0.45)',
  },
  headerTitle: {
    flex: 1,
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: LUNA_COLORS.darkest,
  },
  headerIcon: {
    color: LUNA_COLORS.tertiary,
  },
  body: {
    padding: spacing.lg,
    maxHeight: 420,
    backgroundColor: LUNA_COLORS.surface,
  },
  footer: {
    flexDirection: 'row',
    gap: spacing.md,
    padding: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: LUNA_COLORS.primary,
    backgroundColor: LUNA_COLORS.surfaceLight,
  },
  footerSingle: {
    padding: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: LUNA_COLORS.primary,
    backgroundColor: LUNA_COLORS.surfaceLight,
    alignItems: 'center',
  },
  btnGhost: {
    flex: 1,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: LUNA_COLORS.secondary,
    backgroundColor: LUNA_COLORS.surface,
    alignItems: 'center',
  },
  btnGhostTxt: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    color: LUNA_COLORS.dark,
  },
  btnPrimary: {
    flex: 1,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    backgroundColor: LUNA_COLORS.secondary,
    alignItems: 'center',
  },
  btnPrimaryTxt: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
    color: LUNA_COLORS.textInverse,
  },
  btnCloseOnly: {
    alignSelf: 'center',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    backgroundColor: LUNA_COLORS.secondary,
    minWidth: 120,
    maxWidth: 200,
    alignItems: 'center',
  },
  btnCloseOnlyTxt: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    color: LUNA_COLORS.textInverse,
  },
  btnDanger: {
    flex: 1,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    backgroundColor: LUNA_COLORS.error,
    alignItems: 'center',
  },
  detailLabel: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.semibold,
    color: LUNA_COLORS.tertiary,
    marginTop: spacing.sm,
  },
  detailValue: {
    fontSize: fontSize.base,
    color: LUNA_COLORS.textPrimary,
    marginTop: 2,
  },
  fieldLabel: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semibold,
    color: LUNA_COLORS.dark,
    marginBottom: spacing.xs,
    marginTop: spacing.sm,
  },
  input: {
    backgroundColor: LUNA_COLORS.surface,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: 'rgba(84, 172, 191, 0.5)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    fontSize: fontSize.base,
    color: LUNA_COLORS.textPrimary,
  },
  errBox: {
    backgroundColor: LUNA_COLORS.errorLight,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    marginTop: spacing.md,
  },
  errTxt: { fontSize: fontSize.sm, color: LUNA_COLORS.error },
});
