import {
  IconAlertCircle,
  IconAlertTriangle,
  IconBandage,
  IconBed,
  IconCalendar,
  IconCards,
  IconChartBar,
  IconClipboardList,
  IconContract,
  IconCreditCard,
  IconDeviceMobile,
  IconFileText,
  IconFlask,
  IconFolderOpen,
  IconHeart,
  IconHome,
  IconMedicalCross,
  IconNotes,
  IconPackage,
  IconPill,
  IconPlane,
  IconPlus,
  IconReportMedical,
  IconScan,
  IconSearch,
  IconServer,
  IconShield,
  IconShoppingCart,
  IconStar,
  IconMap,
  IconThermometer,
  IconTools,
  IconUser,
  IconUsers,
  IconClock,
  IconCheck,
  IconCircle,
  IconChecklist,
  IconChevronRight,
  IconBuilding,
  IconMessage,
  IconMessages,
  IconBell,
  IconSettings,
  IconLogout,
  IconCamera,
  IconList,
  IconLayersOff,
  IconGauge,
  IconCalendarTime,
  IconStethoscope,
  type Icon as TablerIcon,
} from '@tabler/icons-react-native';

/**
 * Maps legacy Ionicon names to Tabler icon components.
 * Covers all icon strings used across screen files.
 */
export const IONICON_TO_TABLER: Record<string, TablerIcon> = {
  // Medical / Health
  'medical-outline': IconMedicalCross,
  'medical': IconMedicalCross,
  'pulse-outline': IconStethoscope,
  'pulse': IconStethoscope,
  'heart-outline': IconHeart,
  'heart': IconHeart,
  'bandage-outline': IconBandage,
  'bandage': IconBandage,
  'flask-outline': IconFlask,
  'flask': IconFlask,
  'pill-outline': IconPill,
  'pill': IconPill,
  'thermometer-outline': IconThermometer,
  'thermometer': IconThermometer,
  'bed-outline': IconBed,
  'bed': IconBed,
  'scan-outline': IconScan,
  'scan': IconScan,

  // People / Users
  'people-outline': IconUsers,
  'people': IconUsers,
  'person-outline': IconUser,
  'person': IconUser,
  'person-add-outline': IconUser,

  // Calendar / Time
  'calendar-outline': IconCalendar,
  'calendar': IconCalendar,
  'time-outline': IconClock,
  'time': IconClock,

  // Documents / Files
  'document-text-outline': IconFileText,
  'document-text': IconFileText,
  'folder-open-outline': IconFolderOpen,
  'folder-open': IconFolderOpen,
  'alert-circle-outline': IconAlertCircle,
  'alert-circle': IconAlertCircle,
  'clipboard-outline': IconClipboardList,
  'clipboard': IconClipboardList,
  'list-outline': IconList,
  'list': IconList,
  'checklist-outline': IconChecklist,
  'checklist': IconChecklist,
  'notes-outline': IconNotes,
  'notes': IconNotes,

  // Navigation / Actions
  'home-outline': IconHome,
  'home': IconHome,
  'swap-horizontal-outline': IconMap,
  'swap-horizontal': IconMap,
  'arrow-redo-outline': IconChevronRight,
  'arrow-redo': IconChevronRight,
  'chevron-forward-outline': IconChevronRight,
  'chevron-forward': IconChevronRight,

  // Status / Alerts
  'checkmark-circle-outline': IconCircle,
  'checkmark-circle': IconCircle,
  'checkmark-done-outline': IconCheck,
  'checkmark-done': IconCheck,
  'warning-outline': IconAlertTriangle,
  'warning': IconAlertTriangle,
  'alert-triangle-outline': IconAlertTriangle,
  'alert-triangle': IconAlertTriangle,
  'airplane-outline': IconPlane,
  'airplane': IconPlane,

  // Business / Admin
  'business-outline': IconBuilding,
  'business': IconBuilding,
  'card-outline': IconCreditCard,
  'card': IconCreditCard,
  'layers-outline': IconLayersOff,
  'layers': IconLayersOff,
  'cash-outline': IconShoppingCart,
  'cash': IconShoppingCart,
  'server-outline': IconServer,
  'server': IconServer,
  'construct-outline': IconContract,
  'construct': IconContract,
  'speedometer-outline': IconGauge,
  'speedometer': IconGauge,
  'today-outline': IconCalendarTime,
  'today': IconCalendarTime,

  // Communication
  'chatbubbles-outline': IconMessages,
  'chatbubbles': IconMessages,
  'chatbubble-outline': IconMessage,
  'chatbubble': IconMessage,
  'call-outline': IconDeviceMobile,
  'call': IconDeviceMobile,
  'mail-outline': IconFileText,
  'mail': IconFileText,

  // Misc
  'medkit-outline': IconMedicalCross,
  'medkit': IconMedicalCross,
  'star-outline': IconStar,
  'star': IconStar,
  'search-outline': IconSearch,
  'search': IconSearch,
  'shield-outline': IconShield,
  'shield': IconShield,
  'pricetag-outline': IconStar,
  'pricetag': IconStar,
  'resize-outline': IconTools,
  'resize': IconTools,
  'menu-outline': IconList,
  'menu': IconList,
  'settings-outline': IconSettings,
  'settings': IconSettings,
  'log-out-outline': IconLogout,
  'log-out': IconLogout,
  'camera-outline': IconCamera,
  'camera': IconCamera,
  'bell-outline': IconBell,
  'bell': IconBell,
  'dashboard': IconChartBar,
};

/**
 * Resolves an icon name (Ionicon string or Tabler key) to a Tabler icon component.
 * Falls back to IconMedicalCross if not found.
 */
export function resolveTablerIcon(name: string | undefined | null): TablerIcon {
  if (!name) return IconMedicalCross;
  const lower = name.toLowerCase().replace(/-/g, '-');
  return IONICON_TO_TABLER[lower] ?? IconMedicalCross;
}
