@startuml
!theme plain

title Diagramme de cas d'utilisation - Parcours patient (Sprint 3)

left to right direction
skinparam packageStyle rectangle

actor "Secretaire" as SEC
actor "Medecin" as MED
actor "Infirmier" as INF
actor "Patient" as PAT

rectangle "Module Metier Clinique" {
  usecase "Enregistrer un patient" as UC1
  usecase "Mettre a jour un patient" as UC2
  usecase "Creer le dossier medical" as UC3
  usecase "Consulter le dossier patient" as UC4
  usecase "Affecter un patient a un suivi medical" as UC5
  usecase "Enregistrer une consultation" as UC6
  usecase "Generer une ordonnance" as UC7
  usecase "Demander des examens complementaires" as UC8
  usecase "Planifier un rendez-vous" as UC9
  usecase "Gerer la file d'attente des RDV" as UC10
  usecase "Recevoir un rappel de RDV" as UC11
  usecase "Creer une demande d'operation" as UC12
  usecase "Transmettre une demande a la clinique cible" as UC13
}

SEC --> UC1
SEC --> UC2
SEC --> UC9
SEC --> UC10

MED --> UC4
MED --> UC5
MED --> UC6
MED --> UC7
MED --> UC8
MED --> UC9
MED --> UC12
MED --> UC13

INF --> UC4

PAT --> UC9
PAT --> UC11

UC1 ..> UC3 : <<include>>
UC6 ..> UC7 : <<extend>>
UC9 ..> UC11 : <<include>>
UC12 ..> UC13 : <<extend>>

@enduml
